# Generated by Django 4.1 on 2022-10-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('email', models.EmailField(max_length=120, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_meeting', models.CharField(max_length=120, unique=True, verbose_name='Nome da reunião')),
                ('date_meeting', models.DateField(verbose_name='Data da reunião')),
                ('link', models.CharField(blank=True, max_length=400, verbose_name='Link da reunião')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('public', models.CharField(choices=[('p', 'Publicado'), ('a', 'Arquivado')], default='p', help_text='Publicar ou Arquivar', max_length=1)),
                ('local', models.CharField(choices=[('p', 'Presencial'), ('o', 'Online')], default='p', help_text='Local Reunião', max_length=1)),
                ('status', models.CharField(choices=[('p', 'Público'), ('f', 'Fechado')], default='f', help_text='Status da reunião', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
