# Generated by Django 4.1 on 2022-11-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
