# Generated by Django 4.1 on 2022-08-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirm',
        ),
        migrations.DeleteModel(
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
