# Generated by Django 4.1 on 2022-09-22 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2103d58-3a9d-11ed-8d20-5cc9d363c9a3'), help_text='ID UNICO', primary_key=True, serialize=False),
        ),
    ]
