# Generated by Django 4.1 on 2022-08-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_confirm_delete_meeting_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_meeting', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=120)),
                ('setor', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_meeting', models.CharField(max_length=120)),
                ('date_meeting', models.DateField()),
                ('date_meeting2', models.DateField()),
                ('author', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='polls.owner')),
            ],
        ),
    ]
