# Generated by Django 4.1 on 2022-09-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_funcionario_meeting_alter_meeting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.meeting'),
        ),
    ]
