# Generated by Django 4.1 on 2022-08-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='polls.owner', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name_meeting',
            field=models.CharField(max_length=120, verbose_name='Nome da reunião'),
        ),
    ]
