# Generated by Django 4.1 on 2022-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(help_text='ID UNICO', primary_key=True, serialize=False),
        ),
    ]
