# Generated by Django 4.1 on 2022-09-22 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID UNICO', primary_key=True, serialize=False),
        ),
    ]
