# Generated by Django 4.1 on 2022-09-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmFunc', to='polls.meeting'),
        ),
    ]
