# Generated by Django 4.1 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
