# Generated by Django 4.1 on 2022-09-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_funcionario_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='tags',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='polls.meeting'),
        ),
        migrations.DeleteModel(
            name='UUIDTaggedItem',
        ),
    ]
