# Generated by Django 4.1 on 2022-08-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name', 'email']},
        ),
    ]
