# Generated by Django 4.1 on 2022-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_owner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='public',
            field=models.CharField(choices=[('p', 'Presencial'), ('o', 'Online')], default='f', help_text='Status da reunião', max_length=1),
        ),
    ]
