# Generated by Django 4.1 on 2022-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_meeting_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='public',
            field=models.CharField(choices=[('p', 'Público'), ('f', 'Fechado')], default='f', help_text='Status da reunião', max_length=1),
        ),
    ]
