# Generated by Django 4.1 on 2022-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_meeting_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='public',
        ),
        migrations.AddField(
            model_name='meeting',
            name='local',
            field=models.CharField(choices=[('p', 'Presencial'), ('o', 'Online')], default='p', help_text='Local Reunião', max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('p', 'Público'), ('f', 'Fechado')], default='f', help_text='Status da reunião', max_length=1),
        ),
    ]
