# Generated by Django 4.1 on 2022-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_meeting_public_meeting_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link da reunião'),
        ),
    ]
