# Generated by Django 4.1 on 2022-09-03 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_meeting_borrower_alter_meeting_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='borrower',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
