# Generated by Django 4.1 on 2022-09-05 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0025_meeting_borrower_alter_meeting_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='borrower',
        ),
        migrations.AddField(
            model_name='meeting',
            name='public',
            field=models.CharField(choices=[('p', 'Publicado'), ('a', 'Arquivado')], default='p', help_text='Publicar ou Arquivar', max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
