# Generated by Django 4.1 on 2022-09-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_remove_meeting_borrower_meeting_public_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='public',
            new_name='publicar',
        ),
    ]
