# Generated by Django 4.1 on 2022-09-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_rename_public_meeting_publicar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='publicar',
            new_name='public',
        ),
    ]
