# Generated by Django 4.1 on 2022-09-14 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_rename_publicar_meeting_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
